import { z } from 'zod'

export const npiLookupParametersSchema = z.object({
  number: z.string().optional(),
  enumeration_type: z.string().optional(),
  taxonomy_description: z.string().optional(),
  name_purpose: z.string().optional(),
  first_name: z.string().optional(),
  use_first_name_alias: z.union([z.boolean(), z.string()]).optional(),
  last_name: z.string().optional(),
  organization_name: z.string().optional(),
  address_purpose: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  postal_code: z.string().optional(),
  country_code: z.string().optional(),
  limit: z.number().optional(),
  skip: z.number().optional(),
  max_records: z.number().optional(),
  pretty: z.boolean().optional(),
})

export const perplexitySearchParametersSchema = z.object({
  query: z.string().optional(),
  queries: z.array(z.string()).optional(),
  max_results: z.number().optional(),
  max_tokens: z.number().optional(),
  max_tokens_per_page: z.number().optional(),
  search_mode: z.string().optional(),
  search_domain_filter: z.array(z.string()).optional(),
  search_recency_filter: z.string().optional(),
  search_after_date_filter: z.string().optional(),
  search_before_date_filter: z.string().optional(),
  search_context_size: z.string().optional(),
  country: z.string().optional(),
  user_location: z.record(z.string(), z.unknown()).optional(),
  return_images: z.boolean().optional(),
  return_videos: z.boolean().optional(),
  include_raw_results: z.boolean().optional(),
})

export const perplexityDeepResearchParametersSchema = z.object({
  topic: z.string(),
  depth: z.string().optional(),
  focus_areas: z.array(z.string()).optional(),
  include_trials: z.boolean().optional(),
  include_guidelines: z.boolean().optional(),
  search_domains: z.array(z.string()).optional(),
  time_range: z.string().optional(),
  max_sources: z.number().optional(),
  reasoning_effort: z.string().optional(),
  action: z.string().optional(),
  request_id: z.string().optional(),
  wait_for_completion: z.boolean().optional(),
  initial_delay_seconds: z.number().optional(),
  base_backoff_seconds: z.number().optional(),
  max_backoff_seconds: z.number().optional(),
  max_attempts: z.number().optional(),
})
